language: python
sudo: true

install:
    - pip install tox

script:
    - tox -r

matrix:
    include:
        - env: TOXENV=style
          python: 3.8
          sudo: true

        - python: 3.8
          env: TOXENV=check-manifest
          sudo: true

        - env: TOXENV=docstyle
          python: 3.8
          sudo: true

        - env: TOXENV=py38
          python: 3.8
          sudo: true

        - env: TOXENV=py39
          python: 3.9
          sudo: true

        - env: TOXENV=coverage
          python: 3.8
          sudo: true
